# Generated by Django 4.2.20 on 2025-05-04 08:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(verbose_name="Контент статьи"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True, verbose_name="Краткое саммари в карточке"
            ),
        ),
    ]
