# Generated by Django 4.2.20 on 2025-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commonpages", "0002_feedbackrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        db_index=True,
                        help_text='Это должен быть абсолютный путь, исключая домен. Пример: "/search/".',
                        max_length=255,
                        verbose_name="Старый путь",
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        help_text='Это может быть абсолютный путь или полный URL. Пример: "/search-new/" или "https://example.com/search/".',
                        max_length=255,
                        verbose_name="Новый путь",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, будет ли редирект работать.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Редирект",
                "verbose_name_plural": "Редиректы",
                "ordering": ["-created_at"],
                "unique_together": {("old_path",)},
            },
        ),
    ]
