# Generated by Django 4.2.7 on 2025-01-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Регион"
            ),
        ),
    ]
