# Generated by Django 5.1.9 on 2025-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0003_category_good_catego_parent__c19bc5_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="good_city_id_06f235_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="good_on_stoc_4d85e7_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="good_slug_15f963_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="good_cat_parent_idx",
            old_name="good_catego_parent__c19bc5_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="good_cat_slug_idx",
            old_name="good_catego_slug_3914e5_idx",
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["slug"], name="good_city_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["city", "category", "on_stock"], name="good_city_cat_stock_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="good_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="good_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="good_price_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["time_create"], name="good_time_create_idx"),
        ),
    ]
