# Generated by Django 5.1.9 on 2025-06-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0004_remove_product_good_city_id_06f235_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тега"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание тега"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                (
                    "catalog_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Заголовок на странице каталога",
                    ),
                ),
                (
                    "catalog_description",
                    models.TextField(
                        blank=True, verbose_name="Описание на странице каталога"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Например: применение, марка, тип",
                        max_length=100,
                        verbose_name="Категория тега",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="good_tag_slug_idx"),
                    models.Index(fields=["category"], name="good_tag_category_idx"),
                    models.Index(fields=["is_active"], name="good_tag_active_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="good.tag", verbose_name="Теги"
            ),
        ),
    ]
