# Generated by Django 5.1 on 2024-09-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0005_product_img_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание категории"),
        ),
    ]
