# Generated by Django 5.1 on 2024-09-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0006_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_card_description",
            field=models.TextField(blank=True, verbose_name="Описание в карточке"),
        ),
    ]
