# Generated by Django 5.1 on 2024-09-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0007_product_product_card_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-time_create"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
