# Generated by Django 5.1 on 2024-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0008_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_card_property",
            field=models.TextField(blank=True, verbose_name="Свойства в карточке"),
        ),
    ]
