# Generated by Django 5.1 on 2024-10-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0009_product_product_card_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="good/goods_images",
                verbose_name="Изображение",
            ),
        ),
    ]
