# Generated by Django 5.1 on 2024-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good", "0011_city_product_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="small_text_for_catalog",
            field=models.TextField(
                blank=True, verbose_name="Короткое описание под title каталога"
            ),
        ),
    ]
